### ISSUE TITLE
runtime error: index out of range

### ISSUE THREAD

**Issue by volker-raschek** [makers-bierzo/sds011#1]
Hello I get the following error while executing your example active-read.

```bash
$ sudo ./go-test 
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
github.com/makers-bierzo/sds011.(*sensor).SetMode(0xc0000be050, 0x0, 0x4ef320, 0xc000096260)
        /home/markus/go/pkg/mod/github.com/makers-bierzo/sds011@v0.0.0-20190920232313-f7aab2592d7c/sensor.go:109 +0x10a
main.main()
        /home/markus/workspace/go-test/main.go:22 +0x17e
```

ttyUSB0 is used
```bash
$ ls -la /dev/ttyUSB0 
crw-rw---- 1 root uucp 188, 0  3. Mai 12:30 /dev/ttyUSB0
```

Maybe you can fix this error. I have the Nova SDS011 sensor: https://cdn-reichelt.de/documents/datenblatt/X200/SDS011-DATASHEET.pdf

Volker

**Comment by tokkenno** [comment]
Hello @volker-raschek, I'm confined due to the covid-19 and I don't have the sensor here. I'll fix it as soon as I can.

**Comment by tokkenno** [comment]
Hello @volker-raschek,

I added a response message size check that should have corrected the execution failure.

However, the underlying problem seems to be that the message your sensor responds is not what the program expected. 

Maybe your sensor is not exactly the same model as mine and the communication protocol is also different (the motherboard version of my sensor is 2.18). Based on the PDF file you sent me it looks the same, but without being able to test it directly I can't tell you if there's anything different...
